language: cpp

env:
  matrix:
     ## - UBUNTU_DIST=trusty
     ##   BUILD_TYPE=MinSizeRel
     - UBUNTU_DIST=xenial
       BUILD_TYPE=MinSizeRel
       
services:
  - docker

install: true

script:
  ### build and run tests with docker
  - docker build --build-arg UBUNTU=${UBUNTU_DIST} --build-arg BUILD_TYPE=${BUILD_TYPE} --build-arg -t crabllvm_${UBUNTU_DIST}_${BUILD_TYPE} -f docker/crabllvm-full-size-rel.Dockerfile .

notifications:
   slack: seahornteam:NAUqZmZHFFviPH4ktQbJXgKu
   email:
     recipients:
      - seahorn-build@googlegroups.com
     on_success: always
     on_failure: always
