language: cpp
cache: apt
env:
  matrix:
     ## - UBUNTU_DIST=trusty
     ##   BUILD_TYPE=MinSizeRel
     - UBUNTU_DIST=xenial
       BUILD_TYPE=MinSizeRel
       
services:
  - docker

install: true

script:
  ### build and run tests with docker
  ##- docker build --build-arg UBUNTU=${UBUNTU_DIST} --build-arg BUILD_TYPE=${BUILD_TYPE} -t crabllvm_${UBUNTU_DIST} -f docker/crabllvm-full-size-rel.Dockerfile .
  - docker build --build-arg UBUNTU=${UBUNTU_DIST} --build-arg BUILD_TYPE=${BUILD_TYPE} -t seahorn/crabllvm_llvm_5.0 -f docker/crabllvm-full-size-rel.Dockerfile .
  
  - 'if [ "$TRAVIS_EVENT_TYPE" = "cron" ] ;
        then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          && docker push seahorn/crabllvm_llvm_5.0:latest ;
     fi '

notifications:
   slack: seahornteam:NAUqZmZHFFviPH4ktQbJXgKu
   email:
     recipients:
     - seahorn-build@googlegroups.com
     on_success: always
     on_failure: always


